### ISSUE TITLE
Edit plot notebook to include results of cases with re-distribute internal heat gain (IHG)

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/obc#24]
- [ ] add plot showing room temperature of south and north zone, for base/G36 case, spring/summer/winter season, with/without IHG re-distribute. It will all show in one plot.
- [ ] add two more columns (base/G36 case with redistribute IHG) in plot of annual energy use.

**Comment by JayHuLBL** [comment]
@mwetter I have updated the `post_process.ipynb` based on the latest update from yesterday (branch `issue24_plot_IHG`). It is fine to generate plot showing room temperature of south and north zone for short term simulation, but it will have error to read annual simulation results. Although I have allocated 14 GB memory to my virtual machine, it still gives me the error even at reading the 1st annual result.

**Comment by milicag** [comment]
@JayHuLBL did you try running outside of the notebook?

**Comment by mwetter** [comment]
@JayHuLBL I will need to check when I am back at the lab and have access to the results.

**Comment by JayHuLBL** [comment]
@milicag when running outside of the notebook, it can successfully run first annual case but not the second one.
```
Read annual G36 without diverse loads
Traceback (most recent call last):
  File "run_test.py", line 117, in <module>
    r_base_annual_without_diverse_loads=get_results('annual_base')
  File "run_test.py", line 47, in get_results
    return Reader(file_name, "dymola")
  File "/home/jianjun/GitFolder/BuildingsPy/buildingspy/io/outputfile.py", line 179, in __init__
    self._data_ = DyMatFile(fileName)
  File "/home/jianjun/GitFolder/BuildingsPy/buildingspy/thirdParty/dymat/DyMat/__init__.py", line 44, in __init__
    self.mat = scipy.io.loadmat(fileName, chars_as_strings=False)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio4.py", line 399, in get_variables
    mdict[name] = self.read_var_array(hdr)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio4.py", line 374, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio4.py", line 137, in array_from_header
    arr = self.read_full_array(hdr)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio4.py", line 207, in read_full_array
    return self.read_sub_array(hdr)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio4.py", line 184, in read_sub_array
    arr = arr.copy()
MemoryError
```

**Comment by milicag** [comment]
@JayHuLBL Is there a way to increase the memory allocated to the python kernel? Are you saving in two separate variables (you could merge them later)? I'd also try to keep only 2 weeks per season of data before reading in the other case.

**Comment by JayHuLBL** [comment]
@milicag I checked the Ubuntu system memory usage when running the code. It indicates that the memory easily use out, reduced from 12GB to less than 1GB and then becomes insufficient. 
I did save the two results reading into two separate variables.

**Comment by milicag** [comment]
@JayHuLBL Let's see what Michael suggests. I don't know enough about *.mat files and whether any other data storing files I'm familiar with would be more memory efficient (storing as something else, reading in the second case, etc.).

**Comment by milicag** [comment]
@JayHuLBL One other thing to consider is that python 64 bit is much better at memory allocation.
